---
- hosts: all
  become: yes
  gather_facts: no
  
  tasks:
    - name: Install Python 2.7
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - name: Gather facts after Python is definitely present.
      setup:

    - name: Generate SSH keys
      shell: ssh-keygen -q -t rsa -f /root/.ssh/id_rsa -N ''
      args:
        creates: /root/.ssh/id_rsa

    - name: Allow passwordless SSH between all hosts step1
      shell: /bin/cat /root/.ssh/id_rsa.pub
      register: ssh_keys

    - name: Allow passwordless SSH between all hosts step2
      lineinfile:
        dest: /root/.ssh/authorized_keys
        state: present
        line: "{{ hostvars[item]['ssh_keys']['stdout'] }}"
      with_items: "{{ groups['all'] }}"
#- hosts: ubuntu2
#  become: yes
#  gather_facts: no
#  
#  tasks:
#    - name: Install Python 2.7
#      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
#      changed_when: False
#    - name: Gather facts after Python is definitely present.
#      setup:
