---
- hosts: 192.168.4.2
  become: yes
  gather_facts: no
  
  tasks: 
    - name: Install Python 2.7
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
 
    - name: Gather facts after Python is defnitely present.
      setup:

    - name: Generate /etc/ssh RSA host key
      command: ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C "" -N ""
      args:
        creates: /etc/ssh/ssh_host_rsa_key

- hosts: 192.168.4.3
  become: yes
  gather_facts: no

  tasks: 
    - name: Install Python 2.7
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
 
    - name: Gather facts after Python is defnitely present.
      setup:

    - name: Generate /etc/ssh RSA host key
      command: ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C "" -N ""
      args:
        creates: /etc/ssh/ssh_host_rsa_key
