---
- hosts: all
  become: yes
  gather_facts: no
  
  tasks:
    - name: Install Python 2.7
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - name: Gather facts after Python is definitely present.
      setup:

    - name: Generate SSH keys
      shell: ssh-keygen -q -t rsa -f /root/.ssh/id_rsa -N ''
      args:
        creates: /root/.ssh/id_rsa

    - name: Allow passwordless SSH between all hosts step1
      shell: /bin/cat /root/.ssh/id_rsa.pub
      register: ssh_keys

    - name: Allow passwordless SSH between all hosts step2
      lineinfile:
        dest: /root/.ssh/authorized_keys
        state: present
        line: "{{ hostvars[item]['ssh_keys']['stdout'] }}"
      with_items: "{{ groups['all'] }}"

    - name: For each host, scan for its ssh public key
      shell: "ssh-keyscan {{ item }},`dig +short {{ item }}`"
      with_items: "{{ groups['all'] }}"
      register: ssh_known_host_results
      ignore_errors: yes

    - name: Add/update the public key in the '{{ ssh_known_hosts_file }}'
      known_hosts:
        name: "{{ item.item }}"
        key: "{{ item.stdout }}"
        path: /root/.ssh/known_hosts
      with_items: "{{ ssh_known_host_results.results }}"
#- hosts: ubuntu2
#  become: yes
#  gather_facts: no
#  
#  tasks:
#    - name: Install Python 2.7
#      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
#      changed_when: False
#    - name: Gather facts after Python is definitely present.
#      setup:
